name: Check all birthdays

on:
  workflow_dispatch:
  schedule:
    - cron: 00 03 * * *

jobs:
  reminder:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js version 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm install
      - name: run script
        run: npm run check-birthdays
        env:
          TOKEN: ${{ secrets.TOKEN }}
          MONGO_DB_URI: ${{ secrets.MONGO_DB_URI }}
