name: Check all birthdays

on:
  schedule:
    - cron: 32 13 * * *

jobs:
  reminder:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js version 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: create env file
        run: |
          touch .env
          echo TOKEN=${{ secrets.TOKEN }} >> .env
          echo MONGO_DB_URI=${{ secrets.MONGO_DB_URI }} >> .env
      - run: npm install
      - run: npm run check-birthdays
